Repository geras-papax/VoteGR, pull requests merged in 2021-06, with the labels that each got.

#32 Upgraded connection between android and server
  project_code/VoteGR/app/src/main/java/com/example/votegr/MainActivity.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/history/HistoryFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/parties/PartiesFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/remove_party/RemovePartyFragment.java
  project_code/VoteGR/app/src/main/res/layout/citizen_fragment_history.xml
  project_code/VoteGR/app/src/main/res/layout/select_mode.xml
Labels: enhancement

#34 Add removeParty.php
  project_code/VoteGR-Backend/removeParty.php
  project_code/VoteGR-Backend/voting.php
Labels: enhancement

#38 Logo added - final fixes applied - duplicate code removed
  project_code/VoteGR/app/src/main/java/com/example/votegr/MainActivity.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/add_party/AddPartyViewModel.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/history/HistoryFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/history/HistoryViewModel.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/home/HomeFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/home/HomeViewModel.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/parties/PartiesFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/remove_party/RemovePartyFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/remove_party/RemovePartyViewModel.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/select/SelectFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/select/SelectViewModel.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/statement/StatementFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/statement/StatementViewModel.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/stats/StatsFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/stats/StatsViewModel.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/vote/VoteFragment.java
  project_code/VoteGR/app/src/main/java/com/example/votegr/ui/vote_create/VoteCreateViewModel.java
  project_code/VoteGR/app/src/main/res/layout/citizen_fragment_home.xml
  project_code/VoteGR/app/src/main/res/layout/citizen_fragment_parties.xml
  project_code/VoteGR/app/src/main/res/layout/select_mode.xml
Labels: enhancement

#39 citizen password field added & typo fixed
  project_code/VoteGR-DB/votegr_citizen.sql
  project_code/VoteGR-DB/votegr_users.sql
Labels: bug

#41 Final Versions of Team-plan, Robustness-diagrams, Project-plan
  ΠΑΡΑΔΟΤΕΑ_6_110621/Project-plan-v1.0.docx
  ΠΑΡΑΔΟΤΕΑ_6_110621/Project-plan-v1.0.pdf
  ΠΑΡΑΔΟΤΕΑ_6_110621/Robustness-diagrams-v1.0.docx
  ΠΑΡΑΔΟΤΕΑ_6_110621/Robustness-diagrams-v1.0.pdf
  ΠΑΡΑΔΟΤΕΑ_6_110621/Team-plan-v1.0.docx
  ΠΑΡΑΔΟΤΕΑ_6_110621/Team-plan-v1.0.pdf
Labels: documentation
